version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=animal
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  discovery:
    build: ./eureka
    restart: on-failure
    ports:
      - 8761:8761
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  zuul:
    build: ./zuul
    restart: on-failure
    ports:
      - 9999:9999
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  app:
    depends_on:
      - discovery
      - mysqldb
    build: ./animal
    restart: on-failure
    ports:
      - 8095:8095
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb/animal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  review:
    depends_on:
      - discovery
      - mysqldb
    build: ./review
    restart: on-failure
    ports:
      - 8096:8096
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb/animal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  payment:
    depends_on:
      - discovery
      - mongodb
      - zuul	
    build: ./payment
    restart: unless-stopped
    ports:
      - 3100:3100
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=discovery
      - HOSTNAME=PAYMENT
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=store
      - DB_PORT=
    stdin_open: true
    tty: true
   

volumes:
  db: